import { ENVS } from "@lawcrew/env";
export const appEnvConfigs = {
  PORT: ENVS.PORT,
  NEXT_APP_URI: ENVS.NEXT_APP_URI,
  SESSION_TOKEN_KEY: ENVS.SESSION_TOKEN_KEY,
  CLOUDINARY_CLOUD_NAME: ENVS.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: ENVS.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: ENVS.CLOUDINARY_API_SECRET,
};
